fn main() {
    // The app's own custom commands (close_to_tray, exit_app,
    // manual_check_for_updates) need an explicit ACL permission, same as any
    // plugin command - the main window navigates to http://127.0.0.1:<port>
    // (a "remote" origin, not a local tauri:// asset), and Tauri enforces the
    // ACL on every invoke() from a remote origin regardless of whether the
    // command is a plugin's or the app's own. `.commands()` autogenerates an
    // "allow-<command-with-dashes>" permission per command (see
    // gen/permissions/autogenerated after building) - those identifiers are
    // what capabilities/default.json's permissions list references.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "close_to_tray",
                "exit_app",
                "manual_check_for_updates",
                "get_perf_metrics",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
